---
title: CLOUD KUMPEL
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/"
url: https://cloudkumpel.de
description: Modern Collaboration on Microsoft 365, Azure and more...
avatar: assets/img/fraktalcloud.png
favicon: assets/favicon.ico
header_text: CLOUD KUMPEL
header_feature_image: assets/img/header image.png
footer_text: 'Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type
  on Strap</a>

'
excerpt: true
post_navigation: true
color_image: "/assets/img/lineart.png"
katex: true
mermaid: true
google_analytics: 
cookie_consent: true
color_theme: auto
comments:
  disqus_shortname: 
  cusdis_app_id: 
  utterances:
    repo: Cloud-Kumpel/CloudKumpel
    issue-term: pathname
paginate: 5
paginate_path: "/blog/page:num"
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
exclude:
- ".jekyll-cache"
- ".idea"
- vendor/*
- assets/node_modules/*
remote_theme: sylhare/Type-on-Strap
